// <auto-generated />
using System;
using HomeMaintenance.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeMaintenance.Migrations
{
    [DbContext(typeof(EntityContext))]
    partial class EntityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomeMaintenance.Models.MaintenanceCycleTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("TaskFrequency")
                        .HasColumnType("int")
                        .HasColumnName("TaskFrequency");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TaskName");

                    b.Property<int?>("WeekNumber")
                        .HasColumnType("int")
                        .HasColumnName("WeekNumber");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("MaintenanceCycleTask", (string)null);
                });

            modelBuilder.Entity("HomeMaintenance.Models.TaskExecutionHistory", b =>
                {
                    b.Property<long>("TaskExecutionKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("TaskExecutionKey");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TaskExecutionKey"));

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("RowVersion");

                    b.Property<DateTime>("TaskExecutionDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("TaskExecutionDateTime");

                    b.Property<long>("TaskKey")
                        .HasColumnType("bigint")
                        .HasColumnName("TaskKey");

                    b.Property<string>("TaskNote")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TaskNote");

                    b.Property<string>("TaskPerformedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TaskPerformedBy");

                    b.HasKey("TaskExecutionKey");

                    b.HasIndex("TaskExecutionKey")
                        .IsUnique();

                    b.HasIndex("TaskKey");

                    b.ToTable("TaskExecutionHistory", (string)null);
                });

            modelBuilder.Entity("HomeMaintenance.Models.TaskExecutionHistory", b =>
                {
                    b.HasOne("HomeMaintenance.Models.MaintenanceCycleTask", null)
                        .WithMany("ExecutionHistory")
                        .HasForeignKey("TaskKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeMaintenance.Models.MaintenanceCycleTask", b =>
                {
                    b.Navigation("ExecutionHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
